# Generated by Django 5.2.14 on 2026-07-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("prepayment_date", models.DateField()),
                (
                    "months_reduced",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated number of months reduced from tenure",
                    ),
                ),
                (
                    "interest_saved",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated total interest saved",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepayments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-prepayment_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(
                        help_text="Sequential EMI number (1, 2, 3...)"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "principal_component",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "interest_component",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance after this payment",
                        max_digits=15,
                    ),
                ),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["payment_number"],
                "unique_together": {("loan", "payment_number")},
            },
        ),
    ]
