# Generated by Django 5.2.14 on 2026-08-05 07:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("prepayment_date", models.DateField()),
                (
                    "months_reduced",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated number of months reduced from tenure",
                    ),
                ),
                (
                    "interest_saved",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated total interest saved",
                        max_digits=15,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto_debit", "Auto Debit")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("prepayment", "Prepayment"),
                            ("foreclosure", "Foreclosure"),
                        ],
                        default="prepayment",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("pending", "Pending")],
                        default="paid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepayments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-prepayment_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(
                        help_text="Sequential EMI number (1, 2, 3...)"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "principal_component",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "interest_component",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance after this payment",
                        max_digits=15,
                    ),
                ),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("auto_debit", "Auto Debit"),
                            ("upi", "UPI"),
                            ("netbanking", "Net Banking"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("emi", "EMI"),
                            ("prepayment", "Prepayment"),
                            ("foreclosure", "Foreclosure"),
                        ],
                        default="emi",
                        max_length=20,
                    ),
                ),
                (
                    "additional_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional accrued interest recovered with this EMI.",
                        max_digits=15,
                    ),
                ),
                (
                    "regular_emi_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_debit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["payment_number"],
                "indexes": [
                    models.Index(
                        fields=["loan"], name="payments_pa_loan_id_90cb19_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_7ad4af_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="payments_pa_payment_1d6e55_idx"
                    ),
                    models.Index(
                        fields=["loan", "status"], name="payments_pa_loan_id_4c6d1e_idx"
                    ),
                    models.Index(
                        fields=["loan", "payment_number"],
                        name="payments_pa_loan_id_e27a9b_idx",
                    ),
                ],
                "unique_together": {("loan", "payment_number")},
            },
        ),
    ]
