# Generated by Django 5.2.14 on 2026-09-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="additional_interest",
        ),
    ]
