# Generated by Django 5.2.14 on 2026-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("auto_debit", "Auto Debit"),
                    ("upi", "UPI"),
                    ("netbanking", "Net Banking"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
