# Generated by Django 5.2.14 on 2026-07-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("emi", "EMI"),
                    ("prepayment", "Prepayment"),
                    ("foreclosure", "Foreclosure"),
                ],
                default="emi",
                max_length=20,
            ),
        ),
    ]
