# Generated by Django 5.2.14 on 2026-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_additional_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="request_key",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="prepayment",
            name="request_key",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
