# Generated by Django 5.2.14 on 2026-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepayment",
            name="payment_mode",
            field=models.CharField(
                choices=[("manual", "Manual"), ("auto_debit", "Auto Debit")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prepayment",
            name="payment_type",
            field=models.CharField(
                choices=[("prepayment", "Prepayment"), ("foreclosure", "Foreclosure")],
                default="prepayment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prepayment",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("pending", "Pending")],
                default="paid",
                max_length=20,
            ),
        ),
    ]
