# Generated by Django 5.2.14 on 2026-08-03 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("loans", "0004_loan_closed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="loans.loan",
            ),
        ),
    ]
