# Generated by Django 5.2.14 on 2026-08-05 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("borrower", "Borrower"),
                            ("lender", "Lender"),
                        ],
                        default="guest",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "available_funds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("kyc_verified", models.BooleanField(default=False)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "credit_score",
                    models.PositiveIntegerField(
                        default=750, help_text="CIBIL score approximation"
                    ),
                ),
                (
                    "annual_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
