# Generated by Django 5.2.14 on 2026-08-05 07:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_name", models.CharField(max_length=200)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("home", "Home Loan"),
                            ("car", "Car Loan"),
                            ("education", "Education Loan"),
                            ("personal", "Personal Loan"),
                            ("business", "Business Loan"),
                            ("gold", "Gold Loan"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tenure_years", models.PositiveIntegerField()),
                ("emi", models.DecimalField(decimal_places=2, max_digits=15)),
                ("start_date", models.DateField()),
                (
                    "first_emi_date",
                    models.DateField(
                        blank=True,
                        help_text="Date on which first EMI will be deducted.",
                        null=True,
                    ),
                ),
                (
                    "emi_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "auto_debit",
                    models.BooleanField(
                        default=True, help_text="Automatically deduct EMI on due date."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("default", "Default"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Make visible to lenders for investment",
                    ),
                ),
                (
                    "funded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("returned", "Returned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanDisbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disbursement_number", models.PositiveIntegerField()),
                ("disbursement_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("builder", "Builder Payment"),
                            ("insurance", "Insurance"),
                            ("processing_fee", "Processing Fee"),
                            ("legal", "Legal Charges"),
                            ("technical", "Technical Charges"),
                            ("registration", "Registration"),
                            ("other", "Other"),
                        ],
                        default="builder",
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("released", "Released"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="released",
                        max_length=20,
                    ),
                ),
                ("is_interest_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loan_disbursements",
                "ordering": ["disbursement_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="LoanAccruedInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("emi_date", models.DateField()),
                ("days", models.PositiveIntegerField()),
                (
                    "annual_interest_rate",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "disbursed_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("recovered", "Recovered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recovered_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrued_interests",
                        to="loans.loan",
                    ),
                ),
                (
                    "disbursement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_entries",
                        to="loans.loandisbursement",
                    ),
                ),
            ],
            options={
                "db_table": "loan_accrued_interest",
                "ordering": ["emi_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("agreement", "Loan Agreement"),
                            ("id_proof", "ID Proof"),
                            ("income_proof", "Income Proof"),
                            ("property_papers", "Property Papers"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="loan_documents/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(fields=["loan"], name="loan_disbur_loan_id_64804b_idx"),
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(fields=["status"], name="loan_disbur_status_abbbd8_idx"),
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(
                fields=["disbursement_date"], name="loan_disbur_disburs_5e88dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(
                fields=["loan", "status"], name="loan_disbur_loan_id_037f27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loandisbursement",
            index=models.Index(
                fields=["loan", "disbursement_date"],
                name="loan_disbur_loan_id_bc2dac_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loandisbursement",
            constraint=models.UniqueConstraint(
                fields=("loan", "disbursement_number"),
                name="unique_loan_disbursement_number",
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(fields=["loan"], name="loan_accrue_loan_id_3c84f5_idx"),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(fields=["status"], name="loan_accrue_status_bf4a77_idx"),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(
                fields=["emi_date"], name="loan_accrue_emi_dat_16f92e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(
                fields=["disbursement"], name="loan_accrue_disburs_4d45ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(
                fields=["loan", "status"], name="loan_accrue_loan_id_0efc97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(
                fields=["loan", "emi_date"], name="loan_accrue_loan_id_0e3feb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(
                fields=["loan", "disbursement"], name="loan_accrue_loan_id_c1e956_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccruedinterest",
            index=models.Index(
                fields=["loan", "emi_date", "status"],
                name="loan_accrue_loan_id_2e1788_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanaccruedinterest",
            constraint=models.UniqueConstraint(
                fields=("loan", "disbursement", "from_date", "to_date", "emi_date"),
                name="unique_accrued_interest_cycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanaccruedinterest",
            constraint=models.CheckConstraint(
                condition=models.Q(("interest_amount__gte", 0)),
                name="loan_interest_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanaccruedinterest",
            constraint=models.CheckConstraint(
                condition=models.Q(("days__gte", 0)), name="loan_interest_days_positive"
            ),
        ),
    ]
