# Generated by Django 5.2.14 on 2026-07-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_name",
                    models.CharField(
                        help_text="e.g. Home Loan, Car Loan", max_length=200
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original principal amount",
                        max_digits=15,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate in percent",
                        max_digits=5,
                    ),
                ),
                (
                    "tenure_years",
                    models.PositiveIntegerField(help_text="Loan tenure in years"),
                ),
                (
                    "emi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated monthly EMI",
                        max_digits=15,
                    ),
                ),
                ("start_date", models.DateField(help_text="Date of first EMI")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("default", "Default"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
