# Generated by Django 5.2.14 on 2026-07-24 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="funded_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="loan",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Make visible to lenders for investment"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("home", "Home Loan"),
                    ("car", "Car Loan"),
                    ("education", "Education Loan"),
                    ("personal", "Personal Loan"),
                    ("business", "Business Loan"),
                    ("gold", "Gold Loan"),
                    ("other", "Other"),
                ],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="loan",
            name="emi",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="loan",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure_years",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("returned", "Returned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("agreement", "Loan Agreement"),
                            ("id_proof", "ID Proof"),
                            ("income_proof", "Income Proof"),
                            ("property_papers", "Property Papers"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="loan_documents/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
