# Generated by Django 5.2.14 on 2026-08-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccruedinterest",
            name="emi_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accrued_interest_entries",
                to="payments.payment",
            ),
        ),
    ]
