# Generated by Django 5.2.14 on 2026-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loanaccruedinterest_emi_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loandocument",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandocument",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loandocument",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loandocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("agreement", "Loan Agreement"),
                    ("sanction_letter", "Sanction Letter"),
                    ("insurance", "Insurance"),
                    ("property_papers", "Property Papers"),
                    ("id_proof", "ID Proof"),
                    ("income_proof", "Income Proof"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
