# Generated by Django 5.2.14 on 2026-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_alter_loan_options_loan_funded_amount_loan_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="auto_debit",
            field=models.BooleanField(
                default=True, help_text="Automatically deduct EMI on due date."
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="emi_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half Yearly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="first_emi_date",
            field=models.DateField(
                blank=True,
                help_text="Date on which first EMI will be deducted.",
                null=True,
            ),
        ),
    ]
