# Generated by Django 5.2.14 on 2026-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loan_auto_debit_loan_emi_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="closed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
