# Generated by Django 5.2.14 on 2026-09-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_appearancepreference_bankaccount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loandisbursement",
            name="is_interest_processed",
        ),
        migrations.DeleteModel(
            name="LoanAccruedInterest",
        ),
    ]
