# Generated by Django 5.2.14 on 2026-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_remove_loandisbursement_is_interest_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="request_key",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
