# Generated by Django 5.2.14 on 2026-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_investment_request_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="auto_debit",
            field=models.BooleanField(
                default=False,
                help_text="Enable due-date reminders. No automatic bank debit.",
            ),
        ),
    ]
