# Generated by Django 5.2.14 on 2026-10-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_alter_loan_auto_debit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_palette", models.CharField(default="green", max_length=20)),
                ("default_font", models.CharField(default="auto", max_length=20)),
                ("allow_personal_themes", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="appearancepreference",
            name="color_palette",
            field=models.CharField(default="inherit", max_length=20),
        ),
        migrations.AddField(
            model_name="appearancepreference",
            name="font_style",
            field=models.CharField(default="auto", max_length=20),
        ),
        migrations.AlterField(
            model_name="appearancepreference",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System"),
                    ("palette", "Match color palette"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
