# Generated by Django 5.2.14 on 2026-10-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0010_siteappearance_appearancepreference_color_palette_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="interest_basis",
            field=models.CharField(
                choices=[
                    ("periodic", "Periodic reducing balance"),
                    ("actual_365", "Daily reducing balance (Actual/365)"),
                ],
                default="periodic",
                help_text="Daily interest counts release day, excludes due day, and uses 365 days per year.",
                max_length=20,
            ),
        ),
    ]
